### ISSUE TITLE
Need option to change the AppBar Background color and Back button color.

### ISSUE THREAD

**Issue by TharaniP** [fysoul17/google_maps_place_picker#17]
Hi fysoul17,
      I need to change the AppBar background color based on my app theme and back button color. But there is no option to change those colors in Place Picker. Please provide the same.

 Thanks in advance.

**Comment by fysoul17** [comment]
The main purpose of the package is to select a place with Google Map easily without getting hands dirty. 

Since the overall map design and searching bar is pretty standard, there is no plan to provide customizing app bar nor back button design. However, the package provides customizing place selecting tile at the bottom as it would be very different for every developer based on their app design.

So if you really need to change app bar or back button design, I recommend you to **fork** this project and customize it to match your taste.
