### ISSUE TITLE
Decouple search field from map

### ISSUE THREAD

**Issue by giorgio79** [fysoul17/google_maps_place_picker#50]
Perhaps, you could integrate with one of these

- https://pub.dev/packages/search_map_place
- https://pub.dev/packages/address_search_field

**Comment by fysoul17** [comment]
Hi @giorgio79,
Thanks for the suggestion. ;)

However, decoupling isn't a big issue in terms of coding. I can just put an optional parameter to turn it off. The issue is the purpose of the package. The package originally made for users to pick the location by using autocomplete search and by dragging the pin which is the secondary option to search.

So making the main function as optional sounds weird for me. I will think about providing an optional parameter on next version, but I am not sure whether it will be useful for most cases.

**Comment by giorgio79** [comment]
Yeah just an idea. Maybe not optional, but breaking it apart may make it more manageable. :)

**Comment by abrantesarthur** [comment]
Hi there,

I understand that removing the search field would go against the primary purpose of the package, but I would also greatly appreciate if you could introduce an optional parameter to turn it off. I have a use case where such a feature would be awesome.

Thank you so much for your contribution!!
