### ISSUE TITLE
Restrict northeast and southwest or provide Polygon 

### ISSUE THREAD

**Issue by edwin-alvarez** [fysoul17/google_maps_place_picker#58]
is there any way we can allow address selection only in a given Polygon

**Comment by fysoul17** [comment]
The short answer is No.

Since the package uses [Google map's place API](https://developers.google.com/places/web-service/autocomplete) which does not provide the function you want, it is currently not available with this package.  

You may need to write your own code using other Google map APIs with [Google Map flutter package](https://pub.dev/packages/google_maps_flutter).

**Comment by edwin-alvarez** [comment]
noted, I added an issue under Flutter repo, 

[Restricting Map Bounds](https://github.com/flutter/flutter/issues/63665))

You can close this if you want, once flutter enables the option I'll probably request the option to send the new settings to the base map...

**Comment by fysoul17** [comment]
Will close as there is no further action I cloud support.

Please feel free to re-open the issue when flutter's Google Map package supports the functionality and if there is something I can support.
